# fly.toml app configuration file generated for bookmarker-storer on 2024-10-06T12:41:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bookmarker-storer'
primary_region = 'sjc'

[build]
  image = 'dayosql/bookmarker:latest'

[deploy]
  release_command = "npm run migrate"

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
