[build]
  # Specify the directory where the build output will be stored.
  publish = "dist/bookmarker-storer" 
  # Command to run the Angular build.
  command = "ng build --configuration production"

# Redirect rules to handle Angular routing (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200